[project]
name = "kubex"
dynamic = ["version"]
description = "Asynchronous Kubernetes client inspired by kube.rs"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT License"}
authors = [
    {name = "Codemageddon", email = "dev@codemageddon.me"},
]
maintainers = [
    {name = "Codemageddon", email = "dev@codemageddon.me"},
]
dependencies = [
    "pydantic>=2.0,<3",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/codemageddon/kubex"
Repository = "https://github.com/codemageddon/kubex.git"
Issues = "https://github.com/codemageddon/kubex/issues"
Changelog = "https://github.com/codemageddon/kubex/blob/main/CHANGELOG.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "mypy>=1.11.2",
    "pytest>=8.3.3",
    "ruff>=0.6.8",
]

[tool.hatch.version]
path = "kubex/__version__.py"
